### PR TITLE
doc(standards): get rid of confusing tokens folder

### PR DESCRIPTION
**Pull request by telezhnaya**
Some points why I'm against this grouping:
- For me, it looks like all the standards should be about tokens, we don't have other examples now;
- FT and NFT both have token inside, but they are too different to put them into one category;
- We've made the decision in [Enhanced API](https://github.com/near/near-enhanced-api-server) to use the word `Coin` for FTs and native balance, and `Token` here could be confusing for the users.

### CODE REVIEW

**Comment by telezhnaya** [comment]
I re-checked the links, and they look good. I guess the checker takes the links from master
If you know someone responsible for CI in this project, please ping them

**Comment by frol** [comment]
@telezhnaya Thanks for bringing it up here, and proposing a change that we can review. I feel we need a better structure there. "Tokens" section reflects the common implementation detail, but it does include the native NEAR token here, so it is indeed a bad taxonomy here. Yet, flattening it up to the "Standards" level is also not productive (though, it is not a. blocker)

We will also need to figure out how to configure redirects for the old links as there are way too many of them already shared in various documentation articles, StackOverflow answers, etc. I believe this is actually a huge blocker for this PR to land.

@ori-near We will need some help here from someone who can help organize the setup, so we can easily configure redirects from the old links to the new place

**Comment by ori-near** [comment]
Thank you @telezhnaya for submitting this Nomicon change. As a moderator, I am moving it to the REVIEW stage and would like to ask the @near/wg-contract-standards working group members to assign 1 Technical Reviewer to complete a review (see expectations). If you want to assign yourself, please mention that you are acting as the Technical Reviewer.

Please find some guidelines below for completing the technical review.
<details>
<summary>Technical Review Guidelines</summary>

* First, review the proposal within one week. If you have any suggestions that could be fixed, leave them as comments to the author. It may take a couple of iterations to resolve any open comments.
* Second, once all the suggestions are addressed, produce:
  * A recommendation for the working group for the next step (approve and merge the PR OR reject and close the PR)

Please tag the @near/wg-contract-standards working group once you are done, so they can merge or close the PR. Thanks again.
</details>

**Comment by ori-near** [comment]
As a moderator, we are waiting for the Contract Standards Work Group to have more capacity to review this NEP. We will pause it for now.

**Comment by flmel** [comment]
As the moderator, I assume this PR is no longer active given that there was no activity for very long time. Therefore, I am closing it. If anyone is interested in reopening this PR, please submit a new one.

**Pull request closed without merging**
