### PR TITLE
MT token: Royalties and Payouts A-NEP-Extension 

### PR DESCRIPTION
**Pull request by uncle-T0ny**
Those familiar with the [NEP-199](https://nomicon.io/Standards/Tokens/NonFungibleToken/Payout) payout interface for non-fungible tokens may expect a similar interface for multi token contracts.

### CODE REVIEW

**Comment by frol** [comment]
Hi @uncle-T0ny – thank you for starting this proposal. As the moderator, I labeled this PR as "Needs author revision" because we assume you are still working on it since you submitted it in "Draft" mode.

Please ping the @near/nep-moderators once you are ready for us to review it.

**Comment by frol** [comment]
@uncle-T0ny Thanks for the ping!

I have noticed that you submitted a change to the nomicon instead of a NEP. We are still refining our NEP process, and now we ask people to submit NEPs following [the template](https://github.com/near/NEPs/blob/master/nep-0000-template.md) and adding the document to the `neps` folder of the repo. Once the NEP is approved, we will integrate it into the nomicon (how to automate it is still a work in progress).

**Comment by frol** [comment]
> They are similar to NFT Royalties and Payouts spec and I just added the reference links.

Just for the sake of readability, I would copy the text over, though it is a good idea to have a link at the beginning of the sections mentioning that those sections were inherited from the prior NEPs.

**Comment by uncle-T0ny** [comment]
> @uncle-T0ny Thanks for the ping!
> 
> I have noticed that you submitted a change to the nomicon instead of a NEP. We are still refining our NEP process, and now we ask people to submit NEPs following [the template](https://github.com/near/NEPs/blob/master/nep-0000-template.md) and adding the document to the `neps` folder of the repo. Once the NEP is approved, we will integrate it into the nomicon (how to automate it is still a work in progress).

created https://github.com/near/NEPs/pull/454, this PR I will close

**Pull request closed without merging**
