### PR TITLE
NEP-454 Multi Token Standard Royalties and Payouts

### PR DESCRIPTION
**Pull request by uncle-T0ny**
Those familiar with the [NEP-199](https://nomicon.io/Standards/Tokens/NonFungibleToken/Payout) payout interface for non-fungible tokens may expect a similar interface for multi token contracts.

### CODE REVIEW

**Comment by ori-near** [comment]
Thank you @uncle-T0ny for submitting this NEP.

As a moderator, I reviewed this NEP and it meets the proposed template guidelines. I am moving this NEP to the REVIEW stage and would like to ask the @near/wg-contract-standards working group members to assign 2 Technical Reviewers to complete a technical review (see expectations). If you want to assign yourself, please mention that you are acting as the Technical Reviewers.

Please find some guidelines below for completing the technical review.

<details>
<summary>Technical Review Guidelines</summary>

* First, review the proposal within one week. If you have any suggestions that could be fixed, leave them as comments to the author. It may take a couple of iterations to resolve any open comments.
* Second, once all the suggestions are addressed, produce:
  * A recommendation for the working group if the NEP is ready for voting (it could be approving or rejecting recommendation)
  * A summary of benefits
  * A summary of concerns and blockers that were identified on the way and their status (some will be resolved, others dismissed, etc)
Here is a [nice example](https://github.com/near/NEPs/pull/413#issuecomment-1373211177) and a template for your convenience:
```
## Example
### Recommendation
Add recommendation
### Benefits
* Benefit
* Benefit
### Concerns
| # | Concern | Resolution | Status |
| - | - | - | - |   
| 1 | Concern | Resolution | Status |
| 2 | Concern | Resolution | Status |
```
 
Please tag the @near/nep-moderators once you are done, so we can move this NEP to the voting stage. Thanks again.
</details>

**Comment by frol** [comment]
As a Contract Standards WG member, I believe we should do two things before moving forward with reviewing this NEP:
1. evaluate the necessity of the MT standard as a whole (I [raised this question in the Contract Standards Community Group](https://t.me/nearnft/2358))
2. evaluate the state of the other parts of the standard before we dive into Royalties and Payouts (we had an offline discussion with @uncle-T0ny today, and he might be able to prepare a summary of the gaps of the current MT standard and potentially post it on [Gigs Board](https://devgovgigs.near.social))

**Comment by ori-near** [comment]
As the moderator, I assume this PR is no longer active given that there was no activity for over two months. Therefore, I am closing it. If anyone is interested in reopening this PR, please submit a new one.

**Comment by alexastrum** [comment]
We're currently in the process of getting `mt` approved.
`Royalties and Payouts` should probably be part of that standard, rather than a separate NEP.

**Pull request closed without merging**
