### PR TITLE
MT token: approval management, add owner_id to the mt_is_approved params

### PR DESCRIPTION
**Pull request by uncle-T0ny**

### CODE REVIEW

**Comment by ori-near** [comment]
Hi @uncle-T0ny – thank you for starting this proposal. As the moderator, I labeled this PR as "Needs author revision" because it appears like you are still working on it. 

Please ping the @near/nep-moderators once you are ready for us to review it. We will review it again in early January, unless we hear from you sooner. We typically close NEPs that are inactive for more than two months, so please let us know if you need more time.

**Comment by uncle-T0ny** [comment]
Hi @ori-near, yes, I need more time, because I have more proposals to improve the standard. Currently, I'm working on them. Thanks.

**Comment by uncle-T0ny** [comment]
Hi @ori-near, yes, I need more time, because I have more proposals to improve the standard. Currently, I'm working on them. Thanks.

**Comment by uncle-T0ny** [comment]
@near/nep-moderators
This is a small fix, I think other improvements to the standard should be on different PRs.

**Comment by frol** [comment]
@uncle-T0ny good catch! I wonder how to proceed with this. I feel we should take down the MT standard from the nomicon and get them back to the NEPs (neps folder), and only actually merge MT NEPs after we have a contract implementation that is tested by several parties to ensure that errors like this do not show up.

Would you be open to helping here? Specifically, turn this nomicon page into a NEP (`neps/nep-0421.md`), and let's review the whole MT approval management NEP properly (the original submission was rushed and since that time it seems that no real-world implementations appeared as otherwise, they would uncover this cruel missing piece)

**Comment by victorchimakanu** [comment]
Hello everyone, I'd like to understand the current status of this NEP?

**Comment by flmel** [comment]
As the moderator, I assume this PR is no longer active given that there was no activity for very long time. Therefore, I am closing it. If anyone is interested in reopening this PR, please submit a new one.

**Pull request closed without merging**
